# fly.toml app configuration file generated for tango-video-search on 2024-12-04T19:54:19+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tango-video-search'
primary_region = 'ams'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
